"use client";
import {useCallback,useEffect,useState} from 'react';
import {Activity,RefreshCw,TriangleAlert,Clock3,Database,Camera} from 'lucide-react';
import {Card,CardContent} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Button} from '@/components/ui/button';
type Monitor={photoCollection?:{target:number;checked:number;remaining:number;fivePlus:number;multiple:number;one:number;noPhotos:number;totalPhotos:number;newPhotos:number|null;unavailable:number;errors:number;db:{status:string;finishedAt?:string;errors:number}|null};molit?:{lookbackMonths:number;state:string;processed:number;apartments?:number;regions:number;regionMonths:number;plannedRegions:number;dbStatus:string;matchedProperties:number;matchedTrades:number;unmatched:number;retry:number;finishedAt?:string;paused:boolean;used:number;limit:number;day:string};recovery?:{checkedAt:string;passFinished:boolean;counts:{total:number;completed:number;pending:number;failed:number;excluded:number}};monitorFresh:boolean;checkedAt?:string;health:{state:string;label:string;message:string};collectorAlive?:boolean|null;lastActivityAt?:string;lastSuccessAt?:string;perItemSeconds?:number;summary?:{total:number;details:number;photoProperties:number;photoFiles:number;asOf:string};coverage?:{checkedAt:string;detailDisabled:number;propertyNotProvided:number};run?:{mode?:string;verified?:number;succeeded:number;failed:number;photos:number;current?:{court:string;page?:number;key?:string;caseNumber?:string};syncStatus?:string;error?:string;errors:{key:string;message:string}[]};pipeline?:{finishedAt:string;errors:number;matchedProperties:number;matchedTrades:number;database?:{state:string;errors:number|null;finishedAt:string|null};matching?:{state:string;pending:number|null;message:string}}};
const date=(value?:string)=>value?new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 기록 없음';
export function CourtMonitor(){
 const [data,setData]=useState<(Monitor&{notifications?:{enabled:boolean;last?:{status:string;at:string;error?:string}}})|null>(null);const [error,setError]=useState(false);
 const refresh=useCallback(async()=>{try{const response=await fetch('/api/court-monitor',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error();setData(await response.json());setError(false);}catch{setError(true);}},[]);
 useEffect(()=>{const start=setTimeout(refresh,0);const timer=setInterval(refresh,10000);return()=>{clearTimeout(start);clearInterval(timer);};},[refresh]);
 const stale=!!data&&!data.monitorFresh;const warning=error||stale||!!data&&data.health.state!=='healthy';
 const photo=data?.photoCollection;const molit=data?.molit;const allPhotos=data?.run?.mode==="all-photos";
 const summary=data?.summary;const remaining=summary?Math.max(0,summary.total-summary.details):null;
 const estimatedHours=remaining!==null&&data?.perItemSeconds?remaining*data.perItemSeconds/3600:null;
 return <Card className="border-0 shadow-none"><CardContent className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2"><Activity className="size-5"/>서울·경기 수집 현황</h2><div className="flex items-center gap-2"><Badge variant="outline">{allPhotos?"전체 사진 보강":"자료 수집"}</Badge><Button variant="ghost" size="sm" onClick={refresh}><RefreshCw className="size-4"/>새로고침</Button></div></div>
  <div role="status" aria-live="polite" className={`rounded-xl p-4 ${warning?'bg-rausch/5':'bg-muted'}`}>
   <div className="flex items-center gap-2">{warning?<TriangleAlert className="size-4 text-rausch"/>:<Activity className="size-4"/>}<span className={`font-bold ${warning?'text-rausch':''}`}>{error?'상태 연결 끊김':stale?'감시 신호 끊김':allPhotos&&data?.health.state==='healthy'?'전체 공식 사진 추가 수집 중':data?.health.label??'상태 확인 중'}</span></div>
   <p className="mt-1 text-sm text-muted-foreground">{error?'상태 조회에 실패했습니다. 마지막 기록을 정상 실행의 근거로 판단하지 않습니다.':stale?'감시 기록이 1분 이상 갱신되지 않아 현재 정상 여부를 확인할 수 없습니다.':allPhotos?'기존 물건을 하나씩 열어 법원에서 공개한 사진을 모두 저장하고 있습니다.':data?.health.message??'실제 수집 기록을 불러오고 있습니다.'}</p>
  </div>
  {photo&&<section className="space-y-4 rounded-xl border p-4 md:p-5" aria-label="전체 사진 추가 수집">
   <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="flex items-center gap-2 font-bold"><Camera className="size-4"/>전체 사진 추가 수집</h3><span className="text-sm font-semibold text-rausch">{photo.checked.toLocaleString()} / {photo.target.toLocaleString()}건 확인</span></div>
   <div role="progressbar" aria-label="사진 재확인 진행률" aria-valuenow={photo.checked} aria-valuemin={0} aria-valuemax={photo.target} className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-rausch transition-all" style={{width:`${photo.target?photo.checked/photo.target*100:0}%`}}/></div>
   <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['남은 물건',photo.remaining,'건'],['사진 5장 이상 물건',photo.fivePlus,'건'],['현재 저장된 사진',photo.totalPhotos,'장'],['이번에 추가된 사진',photo.newPhotos,'장']].map(([label,value,unit])=><div key={String(label)} className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold tabular-nums">{typeof value==='number'?value.toLocaleString():'집계 미확정'} <span className="text-xs font-normal">{unit}</span></p></div>)}</div>
   <p className="text-sm">사진 2장 이상 {photo.multiple.toLocaleString()}건 · 1장만 저장 {photo.one.toLocaleString()}건 · 사진 없음 {photo.noPhotos.toLocaleString()}건</p>
   <p className="text-xs text-muted-foreground">전체 대상은 기존 물건 중 종료 확인 물건을 제외한 사진 보강 대상입니다. 사진 5장 이상은 현재 저장된 사진 기준이며, 법원이 1~4장만 공개한 물건도 있습니다. 추가 사진은 이번 수집 전 DB 반영 기록과 비교하며 중복 사진은 제외합니다.</p>
   <p className="text-sm">이번 확인 중 공식 미제공 {photo.unavailable.toLocaleString()}건 · 오류 {photo.errors.toLocaleString()}건</p>
   <p className="text-xs text-muted-foreground">사진 DB 반영: {photo.db?.status==='completed'?`저장 완료 · 오류 ${photo.db.errors}건`:photo.db?.status??'확인 중'} · {date(photo.db?.finishedAt)}. 50건마다 반영하므로 최근 사진은 다음 반영을 기다릴 수 있습니다. 공개 사이트 사진은 파일 배포 후 보입니다.</p>
  </section>}
  {molit&&<section className="space-y-4 rounded-xl border p-4 md:p-5" aria-label="국토부 실거래 현황">
   <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold">국토부 실거래 현황</h3><Badge variant="outline">{molit.paused?'오늘 요청 중지 · 다음 날 자동 재시도':molit.state==='running'?'조회·매칭 중':molit.dbStatus==='completed'?'실거래 DB 반영 완료':molit.state==='partial'?'일부 처리 오류':'조회·매칭 완료 · 사진 DB 완료 대기'}</Badge></div>
   <div className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>서울·경기 경매 아파트 전체</span><strong className="text-rausch">{molit.processed.toLocaleString()} / {molit.apartments?.toLocaleString()??'—'}건 처리 완료</strong></div>
   <div role="progressbar" aria-label="실거래 조회·매칭 진행률" aria-valuenow={molit.processed} aria-valuemin={0} aria-valuemax={molit.apartments??0} className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-rausch transition-all" style={{width:(molit.apartments?Math.min(100,molit.processed/molit.apartments*100):0)+'%'}}/></div>
   <div className="grid grid-cols-2 gap-3 md:grid-cols-3">{[['전체 대상',molit.apartments],['처리 완료',molit.processed],['아직 처리 전',molit.apartments===undefined?undefined:Math.max(0,molit.apartments-molit.processed)],['거래 연결 성공',molit.matchedProperties],['처리 후 미연결',Math.max(0,molit.unmatched-molit.retry)],['처리 오류',molit.retry]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold tabular-nums">{typeof value==='number'?value.toLocaleString():'—'} <span className="text-xs font-normal">건</span></p></div>)}</div>
   <p className="text-sm"><strong>처리 완료 = 연결 성공 + 처리 후 미연결 + 처리 오류</strong>. ‘아직 처리 전’은 이 세 항목에 포함되지 않습니다.</p>
   <p className="text-sm">연결된 물건의 비교 거래 <strong>{molit.matchedTrades.toLocaleString()}건</strong> · {molit.dbStatus==='completed'?'실거래 DB 반영 완료':molit.dbStatus==='failed'?'실거래 DB 반영 오류':'실거래 DB 반영 대기 · 마지막 사진 DB 반영 후 자동 저장'}</p>
   <p className="text-sm">최근 {molit.lookbackMonths}개월 · 조회 지역 {molit.regions.toLocaleString()} / {molit.plannedRegions.toLocaleString()}곳 · 지역·월 {molit.regionMonths.toLocaleString()}개 </p>
   <p className="font-semibold">오늘 API {molit.used.toLocaleString()} / {molit.limit.toLocaleString()}회 사용 · 남은 요청 예산 {Math.max(0,molit.limit-molit.used).toLocaleString()}회</p>
   <p className="text-xs text-muted-foreground">{molit.day} 한국 날짜 기준 앱 요청 예산입니다. API 한 번으로 여러 거래를 받으므로 요청 수와 물건 수는 다릅니다. 비교 거래 수는 물건별 합계라 같은 거래가 여러 물건에 포함될 수 있습니다.</p>
   <p className="text-xs text-muted-foreground">실거래 수치는 이번 조회·매칭 파일 기준입니다. 사진의 마지막 DB 반영이 끝나면 저장한 결과를 자동 반영합니다. ‘처리 후 미연결’은 처리는 끝났지만 조건에 맞는 거래가 없거나 상세·단지 식별정보가 부족하거나 지분·일괄매각으로 직접 비교할 수 없는 물건입니다. 최근 실거래 처리: {date(molit.finishedAt)}.</p>
  </section>}
  <h3 className="font-bold">기존 상세·대표 사진 확보 결과</h3>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{[['전체 대상',data?.recovery?.counts.total??summary?.total],['자료 확보 완료',data?.recovery?.counts.completed],['재확인 대기',data?.recovery?.counts.pending],['수집 실패',data?.recovery?.counts.failed],['종료 확인 · 제외',data?.recovery?.counts.excluded]].map(([label,value])=><div key={label} className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-extrabold tabular-nums">{typeof value==='number'?value.toLocaleString('ko-KR'):'집계 중'}<span className="ml-1 text-xs font-normal text-muted-foreground">건</span></p></div>)}</div>
  <p className="text-sm text-muted-foreground">완료는 상세 화면과 대표 사진을 모두 확보한 물건입니다. 실패에는 재시도했지만 공식 화면이 상세·사진을 제공하지 않은 경우도 포함합니다. 종료가 공식 확인된 미완료 물건은 수집 대상에서 제외하며, 저장 자료는 보존합니다.</p>
  <p className="text-xs text-muted-foreground">저장 자료: 상세 {summary?.details.toLocaleString('ko-KR')??'—'}건 · 사진 있는 물건 {summary?.photoProperties.toLocaleString('ko-KR')??'—'}건. {data?.recovery?.passFinished?'이번 재확인은 끝났습니다. 실패와 제외 사유는 기록에 보존했습니다.':'남은 항목을 재확인 중입니다.'}</p>
  {data?.coverage&&!data?.recovery&&<div className="rounded-xl bg-muted p-4 text-sm"><p className="font-semibold">미확보 사유 · 직전 전체 대조 기준</p><p className="mt-1 text-muted-foreground">상세 버튼 비활성 {data.coverage.detailDisabled.toLocaleString('ko-KR')}건 · 해당 물건 미제공 {data.coverage.propertyNotProvided.toLocaleString('ko-KR')}건. 공식 화면이 상세를 제공하지 않은 항목이며, 재확인 후 새로 제공되는 자료를 저장합니다.</p><p className="mt-1 text-xs text-muted-foreground">사진 미확보에는 상세 미확보 물건과 상세만 있는 물건이 함께 포함됩니다. 조회 완료는 상세·사진 확보 완료와 다릅니다. 대조 시각: {date(data.coverage.checkedAt)}</p></div>}
  <div className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">현재 작업</p><p className="mt-1 font-semibold">{data?.run?.current?`${data.run.current.court} · ${data.run.current.page!==undefined?data.run.current.page+'페이지':data.run.current.caseNumber??'사건 재확인'}`:'아직 기록 없음'}</p><p className="mt-1 break-all text-xs text-muted-foreground">{data?.run?.current?.key}</p></div><div><p className="text-xs text-muted-foreground">이번 실행</p><p className="mt-1 font-semibold">{data?.run?.verified!==undefined?`공식 재확인 ${data.run.verified}건 · `:''}상세 확인·저장 {data?.run?.succeeded??0}건 · 이번 확인 사진 {data?.run?.photos??0}장 · 오류 {data?.run?.failed??0}건</p><p className="mt-1 text-xs text-muted-foreground">{data?.perItemSeconds?`최근 저장 간격 평균 ${data.perItemSeconds.toFixed(1)}초/건`:'처리 속도 측정 중'}</p></div></div>
  <div className="grid gap-3 border-t pt-4 text-xs sm:grid-cols-2"><p><Clock3 className="mr-1 inline size-3.5"/>마지막 저장 성공<br/><span className="mt-1 inline-block font-medium">{date(data?.lastSuccessAt)}</span></p><p><Activity className="mr-1 inline size-3.5"/>감시기 마지막 확인<br/><span className="mt-1 inline-block font-medium">{date(data?.checkedAt)}</span></p><p><Database className="mr-1 inline size-3.5"/>DB 마지막 반영<br/><span className="mt-1 inline-block font-medium">{date(allPhotos?photo?.db?.finishedAt:data?.pipeline?.database?.finishedAt??undefined)} · {allPhotos&&photo?.db?.status==='completed'?'사진 저장 완료 · 오류 '+photo.db.errors+'건':data?.pipeline?.database?.state==='completed'?'저장 완료 · 오류 0건':data?.pipeline?.database?.state==='failed'?'오류 '+data.pipeline.database.errors+'건':'저장 결과 확인 중'}</span></p><p><Camera className="mr-1 inline size-3.5"/>공식 사진 {summary?.photoFiles??'—'}장 · {data?.pipeline?.matching?.state==='paused'?'실거래 매칭 보류 · 기존 자료 유지':`실거래 연결 ${data?.pipeline?.matchedProperties??'—'}개 물건`}</p></div>
  {data?.pipeline?.matching&&data.pipeline.matching.state!=='completed'&&<div className="rounded-xl bg-muted p-4 text-sm"><p className="font-semibold">실거래 매칭 보류</p><p className="mt-1 text-muted-foreground">{data.pipeline.matching.message}</p>{data.pipeline.matching.pending!==null&&<p className="mt-1 text-xs text-muted-foreground">최근 반영 기준 미처리 {data.pipeline.matching.pending.toLocaleString('ko-KR')}개 물건 · DB 저장 오류와 별개입니다.</p>}</div>}
  {(data?.run?.error||!!data?.run?.errors?.length)&&<div className="rounded-xl border border-rausch/20 p-4"><p className="font-semibold text-rausch">최근 수집 오류</p>{data.run.error&&<p className="mt-2 break-words text-xs">{data.run.error}</p>}{data.run.errors.map((e,i)=><p key={i} className="mt-2 break-words text-xs">{e.key} · {e.message}</p>)}</div>}
  {!allPhotos&&estimatedHours!==null&&<p className="text-xs text-muted-foreground">현재 속도로 상세 잔여량만 단순 환산하면 약 {estimatedHours.toFixed(1)}시간입니다. 기존 물건 사진 보강·DB 반영·오류 재시도 시간은 별도이며 실제 완료 시간은 달라집니다.</p>}
  <div className="rounded-xl bg-muted p-3 text-xs"><p className="font-semibold">Windows 오류 알림 {data?.notifications?.enabled?'사용 중':'상태 확인 중'}</p><p className="mt-1 text-muted-foreground">이 화면을 닫아도 감시기가 중단·지연·DB 반영 실패를 감지하면 알립니다. 같은 문제는 반복 알림을 보내지 않습니다.</p>{data?.notifications?.last&&<p className="mt-1 text-muted-foreground">최근 알림: {date(data.notifications.last.at)} · {data.notifications.last.status==='shown'?'Windows 표시 확인':data.notifications.last.status==='submitted'?'Windows 전송 완료 · 표시 여부 미확인':'전송 실패'}{data.notifications.last.status==='failed'&&' — 감시기 로그를 확인해 주세요.'}</p>}</div>
  <p className="text-xs text-muted-foreground">화면은 10초, 감시기는 20초마다 확인합니다. 전체 집계는 최대 1분 간격입니다. 상세 미확보는 사진·상태 확인까지 포함한 전체 잔여량과 다릅니다. 매일 9시 갱신 예약은 중지 상태입니다.</p>
 </CardContent></Card>;
}
